version: '3.5'

services:
  postgres:
    container_name: postgres_setup
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dealmaker
      POSTGRES_DB: dealMakerPostgresDB
    ports:
      - "5432:5432"